# Generated by Django 4.1.7 on 2023-03-05 02:09

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('EID', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Specialization', models.CharField(max_length=100)),
                ('Name', models.CharField(default='Holly Burlew', max_length=100)),
                ('Chamber_Number', models.BigIntegerField(unique=True)),
                ('Day_Availability', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(127), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PID', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(default='Jonathan Dansereau', max_length=100)),
                ('Gov_ID', models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('Gov_ID_Type', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabetic characters are allowed.')])),
                ('Blood_Group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'Ab+'), ('AB-', 'Ab-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True)),
                ('Current_Health', models.CharField(max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('Room_Number', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('RID', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Info', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('EID', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('front_desk', 'Front Desk'), ('data_entry', 'Data Entry')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('TID', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Status', models.CharField(choices=[('Finished', 'Finished'), ('Pending', 'Pending')], default='Pending', max_length=15)),
                ('Test_Type', models.CharField(max_length=100)),
                ('Report_File', models.FileField(unique=True, upload_to='uploads/%Y/%m/%d')),
                ('EID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='Blood_Report_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.test', to_field='Report_File'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('AID', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Status', models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending')], max_length=10)),
                ('EID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
                ('RID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='Admission_Info',
            fields=[
                ('IID', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Date_of_admission', models.DateField(default=datetime.date.today)),
                ('Date_of_discharge', models.DateField(null=True)),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
                ('Room_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.room')),
            ],
        ),
    ]
