# Generated by Django 4.1.7 on 2023-03-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Status',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Name',
            field=models.CharField(default='Torrie Wooten', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Current_Health',
            field=models.CharField(default='Healthy', max_length=1023),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Name',
            field=models.CharField(default='Sherri Neidecker', max_length=100),
        ),
    ]
