# Generated by Django 4.1.7 on 2023-03-05 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_appointment_status_alter_doctor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Name',
            field=models.CharField(default='Matthew Paul', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Blood_Report_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.test', to_field='Report_File'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Name',
            field=models.CharField(default='Kathryn Aumiller', max_length=100),
        ),
    ]
