# Generated by Django 4.1.7 on 2023-03-05 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_doctor_name_alter_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='treatment',
            name='Status',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Name',
            field=models.CharField(default='Elizabeth Andrews', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Name',
            field=models.CharField(default='Susanne Smith', max_length=100),
        ),
    ]
