# Generated by Django 4.1.7 on 2023-03-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_treatment_date_treatment_status_alter_doctor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Name',
            field=models.CharField(default='David Sanchez', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Name',
            field=models.CharField(default='Shirley Poindexter', max_length=100),
        ),
    ]
