# Generated by Django 4.1.7 on 2023-03-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    def create_rooms(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
        Room = apps.get_model('hospital', 'Room')
        for i in range(40):
            room = Room.objects.create(Room_Number=100+i)
            room.save()

    dependencies = [
        ('hospital', '0011_alter_doctor_name_alter_patient_name'),
    ]

    operations = [
        migrations.RunPython(create_rooms),
    ]
