# Generated by Django 4.1.7 on 2023-03-05 17:14

from django.db import migrations


class Migration(migrations.Migration):

    def create_admin(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
        User = apps.get_model('hospital', 'user')
        admin = User.objects.create(EID=1,role='admin',Password_hash='7f3fb8aa28c31354c6548b04afc06716')
        admin.save()
    dependencies = [
        ('hospital', '0012_auto_20230305_1243'),
    ]

    operations = [
        migrations.RunPython(create_admin),

    ]
