# Generated by Django 4.1.7 on 2023-03-06 09:23

from django.db import migrations, models
import names


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_user_username_alter_doctor_name_alter_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Name',
            field=models.CharField(default=names.get_full_name, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Name',
            field=models.CharField(default='Jason Garcia', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=names.get_first_name, max_length=100, unique=True),
        ),
    ]
