# Generated by Django 4.1.7 on 2023-03-06 09:24

from django.db import migrations, models
import names


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_alter_doctor_name_alter_patient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Name',
            field=models.CharField(default='Judy Garcia', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=names.get_first_name, max_length=100),
        ),
    ]
