# Generated by Django 4.1.7 on 2023-03-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_alter_patient_name_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Name',
            field=models.CharField(default='Betty Walter', max_length=100),
        ),
    ]
