# Generated by Django 4.1.7 on 2023-03-06 09:25

from django.db import migrations, models
import names


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_alter_patient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='patient',
            name='Name',
            field=models.CharField(default=names.get_full_name, max_length=100),
        ),
    ]
