# Generated by Django 4.1.7 on 2023-03-06 09:28

from django.db import migrations


class Migration(migrations.Migration):
    def add_data(apps, schema_editor):
        Patient = apps.get_model('hospital', 'Patient')
        patient = Patient.objects.create(Name='Chirag',PID=1,Gov_ID='GHHPM6454S',Gov_ID_Type='PAN',Blood_Group='B-')
        patient.save()
        Doctor = apps.get_model('hospital', 'Doctor')
        doctor = Doctor.objects.create(Name='Anubhav',EID=2,Specialization='Narcology',Chamber_Number=420,Day_Availability=69)
        doctor.save()
        Appointment = apps.get_model('hospital', 'Appointment')
        appt = Appointment.objects.create(AID=1,EID=Doctor.objects.get(EID=2),PID=Patient.objects.get(PID=1))
        appt.save()
    dependencies = [
        ('hospital', '0021_user_name'),
    ]

    operations = [
        migrations.RunPython(add_data)
    ]
