# Generated by Django 4.1.7 on 2023-03-12 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_remove_test_report_file_remove_test_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='RID',
        ),
        migrations.AddField(
            model_name='treatment',
            name='EID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='PID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.patient'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
